/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IT
 */
public class Music extends javax.swing.JFrame {

    /**
     * Creates new form Music
     */
    public Music() {
        initComponents();
        this.setLocationRelativeTo(null);

        bt_guardarCambios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearCancion = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreCancion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sl_puntuacion = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        sp_anio = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        tf_artista = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_album = new javax.swing.JTextField();
        bt_crearCancion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jd_mostrarArchivo = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_texto = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        label_playlist = new javax.swing.JLabel();
        jd_modificarCancion = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreCancion1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sl_puntuacion1 = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        sp_anio1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        tf_artista1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_album1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bt_modifySong = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_nuevaCancion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_canciones = new javax.swing.JTable();
        bt_addToPlaylist = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtb_playlist = new javax.swing.JTable();
        bt_nuevaPlaylist = new javax.swing.JButton();
        bt_eliminarCancion = new javax.swing.JButton();
        bt_eliminarDePlaylist = new javax.swing.JButton();
        bt_modificarEnPlaylist = new javax.swing.JButton();
        bt_modificarCancion = new javax.swing.JButton();
        bt_guardarCambios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_admin = new javax.swing.JMenu();
        jmi_abrirPlaylist = new javax.swing.JMenuItem();
        jmi_cargarPlaylist = new javax.swing.JMenuItem();

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva Canción");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Puntuación:");

        sl_puntuacion.setMaximum(10);
        sl_puntuacion.setMinimum(1);
        sl_puntuacion.setValue(5);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Año:");

        sp_anio.setModel(new javax.swing.SpinnerNumberModel(2020, null, 2020, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Artista:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Álbum:");

        bt_crearCancion.setBackground(new java.awt.Color(255, 255, 255));
        bt_crearCancion.setForeground(new java.awt.Color(255, 255, 255));
        bt_crearCancion.setText("Crear");
        bt_crearCancion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_crearCancion.setContentAreaFilled(false);
        bt_crearCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearCancionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" 1     2     3      4     5      6     7     8      9     10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sl_puntuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_album, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_anio)
                            .addComponent(tf_artista)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_crearCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(sl_puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_anio, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_album, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_crearCancion)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jd_crearCancionLayout = new javax.swing.GroupLayout(jd_crearCancion.getContentPane());
        jd_crearCancion.getContentPane().setLayout(jd_crearCancionLayout);
        jd_crearCancionLayout.setHorizontalGroup(
            jd_crearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_crearCancionLayout.setVerticalGroup(
            jd_crearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ta_texto.setEditable(false);
        ta_texto.setColumns(20);
        ta_texto.setRows(5);
        jScrollPane2.setViewportView(ta_texto);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Playlist/Archivo: ");

        label_playlist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jd_mostrarArchivoLayout = new javax.swing.GroupLayout(jd_mostrarArchivo.getContentPane());
        jd_mostrarArchivo.getContentPane().setLayout(jd_mostrarArchivoLayout);
        jd_mostrarArchivoLayout.setHorizontalGroup(
            jd_mostrarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mostrarArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_mostrarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(jd_mostrarArchivoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_mostrarArchivoLayout.setVerticalGroup(
            jd_mostrarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mostrarArchivoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jd_mostrarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Modificar Canción");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Puntuación:");

        sl_puntuacion1.setMaximum(10);
        sl_puntuacion1.setMinimum(1);
        sl_puntuacion1.setValue(5);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Año:");

        sp_anio1.setModel(new javax.swing.SpinnerNumberModel(2020, null, 2020, 1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Artista:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Álbum:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" 1     2     3      4     5      6     7     8      9     10");

        bt_modifySong.setBackground(new java.awt.Color(255, 255, 255));
        bt_modifySong.setForeground(new java.awt.Color(255, 255, 255));
        bt_modifySong.setText("Modificar");
        bt_modifySong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_modifySong.setContentAreaFilled(false);
        bt_modifySong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifySongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sl_puntuacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_album1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_anio1)
                            .addComponent(tf_artista1)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_modifySong, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_nombreCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(sl_puntuacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_anio1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_artista1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_album1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_modifySong)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jd_modificarCancionLayout = new javax.swing.GroupLayout(jd_modificarCancion.getContentPane());
        jd_modificarCancion.getContentPane().setLayout(jd_modificarCancionLayout);
        jd_modificarCancionLayout.setHorizontalGroup(
            jd_modificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_modificarCancionLayout.setVerticalGroup(
            jd_modificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jelp for Clau");

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        bt_nuevaCancion.setText("+ Cancion");
        bt_nuevaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevaCancionActionPerformed(evt);
            }
        });

        jtb_canciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuación", "Año", "Artista", "Álbum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_canciones);

        bt_addToPlaylist.setText("Agregar a la Playlist");
        bt_addToPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addToPlaylistActionPerformed(evt);
            }
        });

        jtb_playlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntuación", "Año", "Artista", "Álbum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtb_playlist);

        bt_nuevaPlaylist.setText("Crear Playlist");
        bt_nuevaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevaPlaylistActionPerformed(evt);
            }
        });

        bt_eliminarCancion.setText("Eliminar Canción");
        bt_eliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarCancionActionPerformed(evt);
            }
        });

        bt_eliminarDePlaylist.setText("Eliminar de la Playllist");
        bt_eliminarDePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarDePlaylistActionPerformed(evt);
            }
        });

        bt_modificarEnPlaylist.setText("Modificar");
        bt_modificarEnPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarEnPlaylistActionPerformed(evt);
            }
        });

        bt_modificarCancion.setText("Modificar Canción");
        bt_modificarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarCancionActionPerformed(evt);
            }
        });

        bt_guardarCambios.setText("Guardar Cambios");
        bt_guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(bt_nuevaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_eliminarDePlaylist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_modificarEnPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_nuevaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_eliminarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_modificarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_addToPlaylist)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_nuevaCancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_addToPlaylist)
                    .addComponent(bt_eliminarCancion)
                    .addComponent(bt_modificarCancion))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_nuevaPlaylist)
                    .addComponent(bt_eliminarDePlaylist)
                    .addComponent(bt_modificarEnPlaylist)
                    .addComponent(bt_guardarCambios))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jm_admin.setText("Administración");

        jmi_abrirPlaylist.setText("Abrir playlist");
        jmi_abrirPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_abrirPlaylistActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_abrirPlaylist);

        jmi_cargarPlaylist.setText("Cargar playlist");
        jmi_cargarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cargarPlaylistActionPerformed(evt);
            }
        });
        jm_admin.add(jmi_cargarPlaylist);

        jMenuBar1.add(jm_admin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_nuevaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevaCancionActionPerformed
        jd_crearCancion.pack();
        jd_crearCancion.setModal(true);
        jd_crearCancion.setLocationRelativeTo(this);
        jd_crearCancion.setVisible(true);
    }//GEN-LAST:event_bt_nuevaCancionActionPerformed

    private void bt_crearCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearCancionActionPerformed
        String nombre, artista, album;
        int puntuacion, año;

        try {

            nombre = tf_nombreCancion.getText();
            puntuacion = sl_puntuacion.getValue();
            año = Integer.parseInt(sp_anio.getValue().toString());
            artista = tf_artista.getText();
            album = tf_album.getText();

            if (!nombre.equals("") && !artista.equals("") && !album.equals("")) {
                Cancion c = new Cancion(nombre, puntuacion, año, artista, album);

                DefaultTableModel model = (DefaultTableModel) jtb_canciones.getModel();

                Object[] row = new Object[]{
                    c,
                    puntuacion,
                    año,
                    artista,
                    album
                };

                model.addRow(row);

                tf_nombreCancion.setText("");
                sl_puntuacion.setValue(5);
                sp_anio.setValue(2020);
                tf_artista.setText("");
                tf_album.setText("");

                JOptionPane.showMessageDialog(jd_crearCancion, "Canción creada exitosamente.", "Canción creada.", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(jd_crearCancion, "Todos los campos deben llenarse.", "Error de ingreso.", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_bt_crearCancionActionPerformed

    private void jmi_abrirPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_abrirPlaylistActionPerformed
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;

        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filter
                    = new FileNameExtensionFilter(
                            "Arhivos de texto", "txt");
            jfc.setFileFilter(filter);

            int seleccion = jfc.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);

                String linea;

                ta_texto.setText("");

                while ((linea = br.readLine()) != null) {
                    ta_texto.append(linea);
                    ta_texto.append("\n");
                }

                br.close();
                fr.close();

                label_playlist.setText(fichero.getName());

                jd_mostrarArchivo.pack();
                jd_mostrarArchivo.setLocationRelativeTo(this);
                jd_mostrarArchivo.setModal(true);
                jd_mostrarArchivo.setVisible(true);

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_abrirPlaylistActionPerformed

    private void bt_addToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addToPlaylistActionPerformed
        if (jtb_canciones.getSelectedRow() >= 0) {

            int[] rows = jtb_canciones.getSelectedRows();
            for (int i = 0; i < rows.length; i++) {

                Object[] fila = new Object[]{
                    (Cancion)jtb_canciones.getValueAt(rows[i], 0),
                    (Integer)jtb_canciones.getValueAt(rows[i], 1),
                    (Integer)jtb_canciones.getValueAt(rows[i], 2),
                    (String)jtb_canciones.getValueAt(rows[i], 3),
                    (String)jtb_canciones.getValueAt(rows[i], 4)
                };

                DefaultTableModel model = (DefaultTableModel) jtb_playlist.getModel();
                model.addRow(fila);

            }

        }
    }//GEN-LAST:event_bt_addToPlaylistActionPerformed

    private void bt_nuevaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevaPlaylistActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtb_playlist.getModel();

        JFileChooser fc = new JFileChooser("./");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto", "txt");
        fc.setFileFilter(filter);
        int s = fc.showSaveDialog(this);

        if (s == JFileChooser.APPROVE_OPTION) {

            File file;
            if (fc.getFileFilter().getDescription().equals("Archivos de texto")) {
                file = new File(fc.getSelectedFile().getPath() + ".txt");
            } else {
                file = fc.getSelectedFile();
            }

            Playlist p = new Playlist(file);
            for (int i = 0; i < jtb_playlist.getRowCount(); i++) {
                p.getCanciones().add((Cancion) model.getValueAt(i, 0));
            }

            p.escribirArchivo(file.getPath());

            JOptionPane.showMessageDialog(this, "Playlist creada exitosamente.", "Canción creada.", JOptionPane.INFORMATION_MESSAGE);

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

        }
    }//GEN-LAST:event_bt_nuevaPlaylistActionPerformed

    private void jmi_cargarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cargarPlaylistActionPerformed
        File fichero = null;

        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filter
                    = new FileNameExtensionFilter(
                            "Arhivos de texto", "txt");
            jfc.setFileFilter(filter);

            int seleccion = jfc.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();

                selectedFile = fichero;
                Playlist p = new Playlist(fichero);
                DefaultTableModel model = (DefaultTableModel) jtb_playlist.getModel();

                for (int i = model.getRowCount() - 1; i >= 0; i--) {
                    model.removeRow(i);
                }

                for (Cancion cancion : p.getCanciones()) {

                    Object[] fila = new Object[]{
                        cancion,
                        cancion.getPuntuacion(),
                        cancion.getAñoPublicacion(),
                        cancion.getArtista(),
                        cancion.getAlbum()
                    };

                    model.addRow(fila);

                }
                
                bt_guardarCambios.setVisible(true);

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jmi_cargarPlaylistActionPerformed

    private void bt_eliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarCancionActionPerformed
        if (jtb_canciones.getSelectedRow() >= 0) {
            DefaultTableModel model = (DefaultTableModel) jtb_canciones.getModel();
            model.removeRow(jtb_canciones.getSelectedRow());
        }
    }//GEN-LAST:event_bt_eliminarCancionActionPerformed

    private void bt_eliminarDePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarDePlaylistActionPerformed
        if (jtb_playlist.getSelectedRow() >= 0) {
            DefaultTableModel model = (DefaultTableModel) jtb_playlist.getModel();
            model.removeRow(jtb_playlist.getSelectedRow());
        }
    }//GEN-LAST:event_bt_eliminarDePlaylistActionPerformed

    private void bt_modificarEnPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarEnPlaylistActionPerformed
        if (jtb_playlist.getSelectedRow() >= 0) {
            try {
                DefaultTableModel model = (DefaultTableModel) jtb_playlist.getModel();
                
                //int n = jtb_canciones.getSelectedColumn();
                int fila = jtb_playlist.getSelectedRow();
                Cancion c = (Cancion) model.getValueAt(fila, 0);

                selectedCancion = c;
                selectedTable = jtb_playlist;
                
                tf_nombreCancion1.setText(c.getNombre());
                sl_puntuacion1.setValue(c.getPuntuacion());
                sp_anio1.setValue(c.getAñoPublicacion());
                tf_artista1.setText(c.getArtista());
                tf_album1.setText(c.getAlbum());

                jd_modificarCancion.pack();
                jd_modificarCancion.setModal(true);
                jd_modificarCancion.setLocationRelativeTo(this);
                jd_modificarCancion.setVisible(true);
                
                jtb_playlist.setModel(model);
                

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_bt_modificarEnPlaylistActionPerformed

    private void bt_modificarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarCancionActionPerformed
        if (jtb_canciones.getSelectedRow() >= 0) {
            try {
                DefaultTableModel model = (DefaultTableModel) jtb_canciones.getModel();
                

                //int n = jtb_canciones.getSelectedColumn();
                int fila = jtb_canciones.getSelectedRow();
                Cancion c = (Cancion) model.getValueAt(fila, 0);

                selectedCancion = c;
                selectedTable = jtb_canciones;
                
                tf_nombreCancion1.setText(c.getNombre());
                sl_puntuacion1.setValue(c.getPuntuacion());
                sp_anio1.setValue(c.getAñoPublicacion());
                tf_artista1.setText(c.getArtista());
                tf_album1.setText(c.getAlbum());

                jd_modificarCancion.pack();
                jd_modificarCancion.setModal(true);
                jd_modificarCancion.setLocationRelativeTo(this);
                jd_modificarCancion.setVisible(true);
                
                jtb_canciones.setModel(model);
                

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_bt_modificarCancionActionPerformed

    private void bt_guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarCambiosActionPerformed
        try {
            Playlist p = new Playlist(selectedFile);
            for (int i = p.getCanciones().size() - 1; i >= 0; i--) {
                p.getCanciones().remove(i);
            }

            DefaultTableModel model = (DefaultTableModel) jtb_playlist.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                p.getCanciones().add((Cancion) model.getValueAt(i, 0));
            }

            p.escribirArchivo(selectedFile.getPath());

            JOptionPane.showMessageDialog(this, "Se han guardado los cambios de la playlist.", "Guardado.", JOptionPane.INFORMATION_MESSAGE);
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            bt_guardarCambios.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al guardar la playlist.", "Error.", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_bt_guardarCambiosActionPerformed

    private void bt_crearCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearCancion1ActionPerformed
        bt_modifySongActionPerformed(evt);
    }//GEN-LAST:event_bt_crearCancion1ActionPerformed

    private void bt_modifySongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifySongActionPerformed
        String nombre, artista, album;
        int año, puntuacion;

        try {

            nombre = tf_nombreCancion1.getText();
            puntuacion = sl_puntuacion1.getValue();
            año = Integer.parseInt(sp_anio1.getValue().toString());
            artista = tf_artista1.getText();
            album = tf_album1.getText();

            if (!nombre.equals("") && !artista.equals("") && !album.equals("")) {
                

                DefaultTableModel model = (DefaultTableModel) selectedTable.getModel();
                

                selectedCancion.setNombre(nombre);
                selectedCancion.setPuntuacion(puntuacion);
                selectedCancion.setAñoPublicacion(año);
                selectedCancion.setArtista(artista);
                selectedCancion.setAlbum(album);
                
                int row = selectedTable.getSelectedRow();
                
                model.setValueAt(selectedCancion, row, 0);
                model.setValueAt(puntuacion, row, 1);
                model.setValueAt(año, row, 2);
                model.setValueAt(artista, row, 3);
                model.setValueAt(album, row, 4);
                
                JOptionPane.showMessageDialog(jd_modificarCancion, "Canción modificada exitosamente.", "Canción modificada.", JOptionPane.INFORMATION_MESSAGE);
                
                jd_modificarCancion.setVisible(false);
                tf_nombreCancion1.setText("");
                sl_puntuacion1.setValue(5);
                sp_anio1.setValue(2020);
                tf_artista1.setText("");
                tf_album1.setText("");

                selectedTable.setModel(model);
                
                //actualizarTabla(jtb_playlist);
                //actualizarTabla(jtb_canciones);
                
            } else {
                JOptionPane.showMessageDialog(jd_crearCancion, "Todos los campos deben llenarse.", "Error de ingreso.", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_bt_modifySongActionPerformed

    private void actualizarTabla(JTable tabla){
        
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            
            Cancion c = (Cancion) model.getValueAt(i, 0);
            model.setValueAt((Cancion)c, i, 0);
            model.setValueAt(c.getPuntuacion(), i, 1);
            model.setValueAt(c.getAñoPublicacion(), i, 2);
            model.setValueAt(c.getArtista(), i, 3);
            model.setValueAt(c.getAlbum(), i, 0);
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Music.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Music.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Music.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Music.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Music().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addToPlaylist;
    private javax.swing.JButton bt_crearCancion;
    private javax.swing.JButton bt_eliminarCancion;
    private javax.swing.JButton bt_eliminarDePlaylist;
    private javax.swing.JButton bt_guardarCambios;
    private javax.swing.JButton bt_modificarCancion;
    private javax.swing.JButton bt_modificarEnPlaylist;
    private javax.swing.JButton bt_modifySong;
    private javax.swing.JButton bt_nuevaCancion;
    private javax.swing.JButton bt_nuevaPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_crearCancion;
    private javax.swing.JDialog jd_modificarCancion;
    private javax.swing.JDialog jd_mostrarArchivo;
    private javax.swing.JMenu jm_admin;
    private javax.swing.JMenuItem jmi_abrirPlaylist;
    private javax.swing.JMenuItem jmi_cargarPlaylist;
    private javax.swing.JTable jtb_canciones;
    private javax.swing.JTable jtb_playlist;
    private javax.swing.JLabel label_playlist;
    private javax.swing.JSlider sl_puntuacion;
    private javax.swing.JSlider sl_puntuacion1;
    private javax.swing.JSpinner sp_anio;
    private javax.swing.JSpinner sp_anio1;
    private javax.swing.JTextArea ta_texto;
    private javax.swing.JTextField tf_album;
    private javax.swing.JTextField tf_album1;
    private javax.swing.JTextField tf_artista;
    private javax.swing.JTextField tf_artista1;
    private javax.swing.JTextField tf_nombreCancion;
    private javax.swing.JTextField tf_nombreCancion1;
    // End of variables declaration//GEN-END:variables

    File selectedFile;
    Cancion selectedCancion;
    JTable selectedTable;

}
